### ISSUE TITLE
Upload behavior

### ISSUE THREAD

**Issue by gedankenstuecke** [gedankenstuecke/oh_data_uploader#1]
Right now the uploader 

- will always delete all the files that are already associated with a given project if a user uploads a new file. 
- users can only upload a single file, there is no way to upload multiple files. 

This behaviour should be changed to allow users to 
- keep older files in their account
- allow multiple files being stored

Ideally this would also allow users to display the files already in their accounts and give the option to delete individual files?

**Comment by jasmine1997** [comment]
Hi, I'd like to take this up!

**Comment by jasmine1997** [comment]
Starting to work on this! :)

**Comment by gedankenstuecke** [comment]
That's awesome and a potentially big chunk of work. For a start I think it would be great to focus on 

1. listing the file(s) already associated with the project
2. adding a "delete" button to that file display that uses the API call to delete the file.

Adding a support for allowing multiple uploads is probably more work, as this should ideally go along with changes to the `project_admin` model to support multiple file-upload-forms and meta data.

**Comment by gedankenstuecke** [comment]
@jasmine1997 Just checking in, any issues that arose or that you need help with? 😃

**Comment by jasmine1997** [comment]
I'm not too sure about where to show the file list, but I've tried something. A screenshot is attached in the PR.

About multiple uploads, adding support for multiple file-upload-forms seems straightforward, but I'm a bit confused about the metadata.
Do we want the administrator to decide metadata for all files beforehand, or ask the user to type it in?

**Comment by jasmine1997** [comment]
@gedankenstuecke What's your opinion on this? ^^^

**Comment by gedankenstuecke** [comment]
First of all: Sorry for not having reviewed the updated PR yet. I'll hopefully get around to it later today! 

For the multiple uploads: The metadata should be set by the administrator of the project beforehand E.g. an admin might want to allow people to upload two different data files. File 1 should have its own, admin-defined set of tags along with its own description and File 2 should have a different set of tags/description. 

So this would mean to add this support for multiple files on the admin-backend too.
