### ISSUE TITLE
Update Pipfile

### ISSUE THREAD

**Issue by gedankenstuecke** [gedankenstuecke/oh_data_uploader#12]
All the other Open Humans projects are now moving from using `pip` and `virtualenv`/`anaconda` separately to using `pipenv`, e.g. see https://github.com/OpenHumans/oh-proj-management. 

We should follow along with this project as it's much nicer and easier. To do this the `requirements.txt` needs to be used to seed the `Pipfile` and a `Pipfile.lock` needs to be created. Afterwards the `Pipfile` should be set up so it doesn't use fixed versions any more. Both `Pipfile` and `Pipfile.lock` should be added to this repo

Additionally the `INSTALL.md` needs to be updated to reflect this.

**Comment by manaswinidas** [comment]
I am interested to work on this!

**Comment by gedankenstuecke** [comment]
Thanks so much for wanting to work on this. @madprime's PR in #13 did good parts of this. Having said this, the `Pipfile` still contains the versions that could be deleted from the file and be replaced with `*` instead.

**Comment by gedankenstuecke** [comment]
Also the Pipfile should now use the `PyPi` version of `open-humans-api` instead of a GH linked version as the update is available now. The `Pipfile.lock` should be regenerated afterwards.
