### ISSUE TITLE
Highlight which fields are required in project admin

### ISSUE THREAD

**Issue by gedankenstuecke** [gedankenstuecke/oh_data_uploader#16]
This app only works if a couple of fields are set in the project admin:

Amongst these are 

1. Client ID
2. Client Secret
3. File Description
4. File tags

The `project admin` page needs to make more clear that these fields are required.

**Comment by manaswinidas** [comment]
I am interested to fix this.

**Comment by troublemagnet** [comment]
@manaswinidas  Sorry for not specifying on the issue, but I'm almost ready to make a PR.

**Comment by manaswinidas** [comment]
Okay, that's great! Carry on.
