### ISSUE TITLE
Redirect to project-admin

### ISSUE THREAD

**Issue by gedankenstuecke** [gedankenstuecke/oh_data_uploader#17]
If the fields described in #16 aren't entered the application won't work. Ideally the `index` page should then automatically redirect to the `project-admin login` page or at least provide a large information that says `This app doesn't work yet, go to the admin interface to set up`. 

E.g. the `login` button for regular users could then also hint to the project admin page.

**Comment by troublemagnet** [comment]
I'd like to take this up.
