### ISSUE TITLE
Extending tests

### ISSUE THREAD

**Issue by gedankenstuecke** [gedankenstuecke/oh_data_uploader#26]
To make a start I added two very simple tests to `main/tests.py` with #25. In addition to the tests themselves I also [added continuous integration through `Travis`](https://travis-ci.org/gedankenstuecke/oh_data_uploader). 

This will run all the tests automatically for open pull requests and commits. So far the test covers the presence of the index page and that's it. I'd appreciate any help in extending the tests both in terms of unit as well as integration tests. The [*Django* documentation has extensive hints on how to do this](https://docs.djangoproject.com/en/2.0/topics/testing/).

**Comment by manaswinidas** [comment]
I'm interested!

**Comment by gedankenstuecke** [comment]
Thanks @manaswinidas. Maybe comment on which functions you want to write tests for first, so that there's no duplication of efforts :)

**Comment by gedankenstuecke** [comment]
I also wrote some tests in #30

**Comment by troublemagnet** [comment]
I was wondering if it was a good idea to add style tests at this point?

**Comment by gedankenstuecke** [comment]
sure, that sounds good 👍

**Comment by manaswinidas** [comment]
I wrote some tests in #33

**Comment by gedankenstuecke** [comment]
I updated our CI integration a bit. 

Besides running the regular test suite with `TravisCI` we are now also automatically running `HoundCI`. Hound uses `flake8` and will report any style-breaking changes it finds in a pull request.

In addition to this I integrated our `TravisCI` with `CodeClimate` which will check each pull request for the general code quality and the test coverage and will complain on pull requests too.

**Comment by troublemagnet** [comment]
@gedankenstuecke I'm testing the add files function.

**Comment by gedankenstuecke** [comment]
Please make sure to use the current master branch, because I already added some tests for this 👍

**Comment by troublemagnet** [comment]
Sorry, my bad. Just pulled.

**Comment by gedankenstuecke** [comment]
No problem, https://codeclimate.com/github/gedankenstuecke/oh_data_uploader/code?sort=test_coverage gives you a list of the files and how much they are covered, clicking on a single file you can switch to the `code` tab and enable the `coverage` highlighting and it will you show all the lines that aren't covered for a single file in red. This should be useful for seeing what tests are missing so far. :)

**Comment by gedankenstuecke** [comment]
Ok, by now the [test coverage has improved from 0% to 92%](https://codeclimate.com/github/gedankenstuecke/oh_data_uploader), thanks to everyone here! 🎉

There are still minor things which are untested that largely concern error handling. If someone wants to improve on that, I'll for now not meddle with these.

**Comment by troublemagnet** [comment]
Hey everyone, I'm currently testing delete_file in project_admin/views.

**Comment by gedankenstuecke** [comment]
Closing this for now as we've nearly reached 100% test coverage. 👍 🎉
