### ISSUE TITLE
Display error on file upload table

### ISSUE THREAD

**Issue by gedankenstuecke** [gedankenstuecke/oh_data_uploader#48]
<img width="1552" alt="screen shot 2018-03-05 at 10 38 57" src="https://user-images.githubusercontent.com/674899/36993834-0cb5451c-2064-11e8-81b3-96407ab26635.png">

The file upload table is a bit broken right now in terms of the display: The horizontal lines extend out over the boundaries of the upload field and parts of the horizontal line of the header seems to be doubled. See the screenshot above.

**Comment by manaswinidas** [comment]
This requires using the `oh-data-source-template` for adding data to reach this page?

**Comment by gedankenstuecke** [comment]
No, the easiest way to do it is to set up a test OAuth2 project for yourself in Open Humans as described in the README and then give the client key/secret credentials in the admin backend of this repo when you run it locally with `heroku local`. Then you can sign in into your development project and get to the file upload page.

**Comment by manaswinidas** [comment]
Thanks, I'm taking this up.
